### ISSUE TITLE
Unrecognized GitHub link with trailing "/"

### ISSUE THREAD

**Issue by szpak** [aaronpk/indielogin.com#59]
The following link:
> `<link href="https://github.com/nonexistingone/" rel="me">`

is found and displayed by indielogin.com, but is not recognized as GitHub. With the trailing `/` removed it works.

Maybe matching with URLs could be extended to accept trailing `/`. They are valid links to those services.

Similar to #16, but different.

**Comment by aaronpk** [comment]
Can you try again? I just pushed some changes that should solve this.

**Comment by szpak** [comment]
I will try to check it doing the next update on my blog. If you think it should be fixed, let's close this issue. I will reopen it when needed.

Thanks for taking a look at that.

**Comment by contentedweb** [comment]
Just to let you know, this is still an issue.  I have two sites using webmention.io.  On one the "rel=me" link ended with a slash, on the other not.  The one with a trailing slash was not recognised as github. indielogin found the rel link, but told me it was not a valid authentication provider.  Was a little confusing, but thanks to reading this issue I removed the trailing slash and now it works.

Maybe re-open the issue?

**Comment by missmatsuko** [comment]
<img width="676" alt="Login issue" src="https://user-images.githubusercontent.com/17884198/117082420-138f7380-acf7-11eb-918d-320085e68c9b.png">
> Your GitHub profile linked to https://www.matsuko.ca/ but we were expecting to see https://www.matsuko.ca/. Make sure you link to https://www.matsuko.ca/ in your GitHub profile.

I had the same problem. Removing the trailing slash worked. 

Would it be possible to not requiring specify the protocol as well, or would that cause issues? I kind of like having just `www.matsuko.ca` on my GitHub profile but I had to add `https://` to authenticate for this.

**Comment by lauras** [comment]
I'm having the same problem trying to log in using GitHub. I tried with two different websites linked in my GitHub profile (and linked back from the sites fwiw), but I just get an error:

> GitHub profile links to [A] but we were expecting to see [A]. Make sure you link to [A] in your GitHub profile.

…which only leaves me mystified. I even tried adding the trailing slash, but that made no difference.

**Comment by lauras** [comment]
Actually I have to correct my post above because I'm realizing that none of my profile links are seen, if I'm reading this error text right.
![Screenshot of SafariScreenshot of Safari (4-7-23, 2-41-02 PM)](https://user-images.githubusercontent.com/181019/230676442-e5b34fe8-cc5d-46a3-a321-6ac16dfa05c2.jpg)
![Screenshot of SafariScreenshot of Safari (4-7-23, 2-43-18 PM)](https://user-images.githubusercontent.com/181019/230676463-a7080ca1-8c38-4e1a-9b28-14bd71793445.jpg)

**Comment by aaronpk** [comment]
If any of you are still experiencing this problem, can you go here and click through and paste a screenshot of what you see?

https://indielogin.com/debug

I'm trying to track down the actual cause of this but I haven't been able to figure it out.
